export type Expression = { kind: "number"; value: number; }
    | { kind: "boolean"; value: boolean; }
    | { kind: "ident"; name: string; }
    | { kind: "binop"; op: Binop; left: Expression; right: Expression; }
    | { kind: "unop"; op: Unop; child: Expression; };

// GENERATED BY src/generators/gengram.py

export type Unop = "POS" | "LOGNOT" | "NEG" | "BITNOT";

export type Binop = "MOD" | "SUBLSHIFT" | "DIV" | "BITXOR" | "EXPN"
    | "LT" | "GT" | "BITOR" | "GTEQ" | "BITAND"
    | "LTEQ" | "ADD" | "RSHIFT" | "LOGANDLOGOR" | "ISEQNOTEQ"
    | "MULT";